def ayuda():
    print('Comandos disponibles en transform:')
    print('  linearpattern  - Crea un patrón lineal (repetición en línea recta)')
    print('  mirrored       - Crea una simetría (espejo) de operaciones seleccionadas')
    print('  polarpattern   - Crea un patrón polar (repetición circular)')
    print('  multitransform - Aplica múltiples transformaciones sucesivas combinadas')
    print('  scaled         - Crea copias escaladas progresivamente (sub-herramienta de MultiTransform)')
    print('\nPrecondiciones:')
    print('  - Todos los comandos requieren que exista un Body activo.')
    print('  - Todos los comandos de transformación requieren seleccionar previamente una o más características/operaciones (features) en el árbol.')
