def ayuda():
    print('Comandos disponibles en manage:')
    print('  movefeature       - Mueve un objeto desde un Body hacia otro Body')
    print('  movefeatureintree - Reordena objetos dentro del árbol de un Body')
    print('  movetip           - Define una operación como la Punta (Tip) del Body')
    print('  preferences       - Abre las preferencias de FreeCAD / PartDesign')
    print('  wizardshaft       - Asistente para crear ejes con análisis de fuerzas')
    print('\nPrecondiciones:')
    print('  - movefeature y movefeatureintree requieren tener seleccionada una característica (feature) del árbol.')
    print('  - movetip requiere tener seleccionada una característica del Body activo para definirla como Tip.')
