def ayuda():
    print('Comandos disponibles en este nivel:')
    print('  bezier  - Crea una curva de Bézier de grado N según la cantidad de puntos.')
    print('            Requiere: pointslist (Lista de Vectores).')
    print('            Nota: El grado de la curva depende del número de puntos.')
    print('')
    print('  bspline - Crea una curva suave (B-Spline) que pasa por puntos de control.')
    print('            Requiere: pointslist (Lista de Vectores), closed (Booleano).')
    print('            Nota: Similar al wire, pero aplica suavizado entre puntos.')
    print('')
    print('  cubic   - Crea una curva de Bézier de tercer grado (cúbica).')
    print('            Requiere: pointslist (Lista de 4 Vectores para una cúbica simple).')
    print('            Nota: Requiere puntos de control para definir la curvatura (grado 3).')