def ayuda():
    print('Comandos disponibles en additive:')
    print('  pad               - Extruye un sketch para crear un sólido (Pad)')
    print('  revolution        - Crea un sólido de revolución a partir de un sketch')
    print('  additivehelix     - Crea un sólido barriendo un perfil en trayectoria helicoidal')
    print('  additiveloft      - Crea un sólido con transición suave entre múltiples perfiles')
    print('  additivepipe      - Crea un sólido barriendo un perfil a lo largo de un camino')
    print('  additivebox       - Inserta un cubo primitivo aditivo')
    print('  additivecone      - Inserta un cono primitivo aditivo')
    print('  additivecylinder  - Inserta un cilindro primitivo aditivo')
    print('  additiveellipsoid - Inserta un elipsoide primitivo aditivo')
    print('  additiveprism     - Inserta un prisma regular primitivo aditivo')
    print('  additivesphere    - Inserta una esfera primitiva aditiva')
    print('  additivetorus     - Inserta un toroide primitivo aditivo')
    print('  additivewedge     - Inserta una cuña primitiva aditiva')
    print('\nPrecondiciones:')
    print('  - Todos los comandos requieren que exista un Body activo.')
    print('  - pad, revolution, additivehelix, additiveloft y additivepipe requieren seleccionar previamente un boceto (sketch).')
