def ayuda():
    print("Comandos disponibles en Array:")
    print("- circular: Crea una matriz circular distribuyendo copias de un objeto.")
    print("  Requiere: objeto base, número de copias, ángulo, centro.")
    print("")
    print("- ortho: Crea una matriz ortogonal de copias en X, Y y Z.")
    print("  Requiere: objeto base, espaciado en X, Y, Z, cantidad en X, Y, Z, usar link.")
    print("")
    print("- polar: Crea una matriz polar distribuyendo copias alrededor de un centro.")
    print("  Requiere: objeto base, ángulo, cantidad de copias, centro, usar link.")
    print("")
    print("- path: Distribuye copias de un objeto a lo largo de una trayectoria.")
    print("  Requiere: objeto base, trayectoria, cantidad de copias.")
    print("")
    print("- path_link: Distribuye enlaces (Links) a lo largo de una trayectoria.")
    print("  Requiere: objeto base, trayectoria, cantidad de copias.")
    print("")
    print("- point: Distribuye copias en posiciones definidas por puntos.")
    print("  Requiere: objeto base, objeto contenedor de puntos.")
    print("")
    print("- point_link: Distribuye enlaces (Links) en posiciones definidas por puntos.")
    print("  Requiere: objeto base, objeto contenedor de puntos.")
