def ayuda():
    print('Comandos disponibles en subtractive:')
    print('  pocket               - Sustrae material extrudiendo un sketch hacia el interior (vaciado)')
    print('  groove               - Sustrae material girando un sketch alrededor de un eje (ranura)')
    print('  hole                 - Crea orificios roscados o sin rosca a partir de un sketch')
    print('  subtractivebox       - Sustrae un prisma rectangular del sólido activo')
    print('  subtractivecone      - Sustrae un cono del sólido activo')
    print('  subtractivecylinder  - Sustrae un cilindro del sólido activo')
    print('  subtractiveellipsoid - Sustrae un elipsoide del sólido activo')
    print('  subtractivehelix     - Sustrae material barriendo un sketch en trayectoria helicoidal')
    print('  subtractiveloft      - Sustrae material interpolando entre múltiples perfiles')
    print('  subtractivepipe      - Sustrae material barriendo un sketch a lo largo de una trayectoria')
    print('  subtractiveprism     - Sustrae un prisma poligonal regular del sólido activo')
    print('  subtractivesphere    - Sustrae una esfera del sólido activo')
    print('  subtractivetorus     - Sustrae un toro del sólido activo')
    print('  subtractivewedge     - Sustrae una cuña del sólido activo')
    print('  boolean              - Realiza operaciones booleanas entre sólidos (unión, intersección, diferencia)')
    print('  thickness            - Crea un sólido con paredes de espesor definido a partir de un sólido base')
    print('  wizardshaft          - Asistente para crear ejes con características comunes')
    print('\nPrecondiciones:')
    print('  - Todos los comandos requieren que exista un Body activo con un sólido base.')
    print('  - pocket, groove, hole, subtractivehelix, subtractiveloft y subtractivepipe requieren seleccionar previamente un boceto (sketch).')
    print('  - boolean requiere exactamente dos cuerpos solidos selccionados')
    print('  - thickness requiere un solido y seleccion de caras a eliminar')