"""
main.py
Program that uses the Keychain class to extract top-level keys and icons
from a dictionary defined in a .py file inside the 'dic' folder.

Supports both:
- Literal dictionaries (e.g., {'icon': 'path/icon.svg'})
- Dictionaries with imports and variable references (e.g., explorer.py)

Shows keys and, if they map to icon paths, displays the icon information
and opens the existing icons with the default application.
"""
import os
import sys
import subprocess
from Keychain import Keychain   # <-- IMPORT ADDED HERE


def open_file(path):
    """Open a file with the system's default application."""
    if sys.platform == 'win32':
        os.startfile(path)
    elif sys.platform == 'darwin':
        subprocess.run(['open', path])
    else:  # Linux and other Unix-like
        subprocess.run(['xdg-open', path])


def main():
    """Main program entry point."""
    # Get the directory where this script is located
    script_dir = os.path.dirname(os.path.abspath(__file__))
    dic_folder = os.path.join(script_dir, "dic")

    # Verify the 'dic' folder exists
    if not os.path.isdir(dic_folder):
        print(f"Error: 'dic' folder not found in {script_dir}")
        print("Please create a 'dic' folder next to this script.")
        return

    # Ask user for the dictionary file name
    file_name = input("Enter the dictionary file name (e.g., explorer.py): ").strip()
    full_path = os.path.join(dic_folder, file_name)

    # Verify the file exists
    if not os.path.isfile(full_path):
        print(f"Error: File '{file_name}' does not exist inside 'dic' folder.")
        # Show available files in dic folder
        try:
            available = os.listdir(dic_folder)
            py_files = [f for f in available if f.endswith('.py')]
            if py_files:
                print("\nAvailable .py files in 'dic' folder:")
                for f in py_files:
                    print(f"  - {f}")
        except Exception:
            pass
        return

    try:
        # Create Keychain instance with the file path
        keychain = Keychain(full_path)

        # Get keys using the smart method (tries both approaches)
        print("\nProcessing file...")
        keys = keychain.GetAllKeys()

        # Get icons, checking existence in the same directory as the dictionary file
        dict_dir = os.path.dirname(full_path)
        icons = keychain.GetIcons(base_dir=dict_dir)

        # Display results header
        print(f"\n{'='*60}")
        print(f"File: {file_name}")
        print(f"Total keys found: {len(keys)}")
        print(f"{'='*60}")

        # Show keys section
        if keys:
            print("\n--- Top-Level Keys ---")
            for i, key in enumerate(keys, 1):
                print(f"  {i:3d}. {key}")
            print("----------------------")
        else:
            print("\nNo dictionary keys found in the file.")
            print("Make sure the file contains a dictionary definition like:")
            print("  my_dict = {'key1': value1, 'key2': value2}")

        # Show icons section (only those that exist)
        if icons:
            print(f"\n--- Icons ({len(icons)} total, existing files) ---")
            for i, icon in enumerate(icons, 1):
                # Check if the icon has an SVG extension
                if icon.endswith('.svg'):
                    icon_display = f"🖼️  {icon}"
                elif icon.endswith('.png'):
                    icon_display = f"🖼️  {icon}"
                else:
                    icon_display = f"📄 {icon}"

                print(f"  {i:3d}. {icon_display}")
            print("----------------------")

            # Additional icon summary
            svg_count = sum(1 for icon in icons if icon.endswith('.svg'))
            png_count = sum(1 for icon in icons if icon.endswith('.png'))
            other_count = len(icons) - svg_count - png_count

            print(f"\nIcon Summary:")
            if svg_count > 0:
                print(f"  - SVG icons: {svg_count}")
            if png_count > 0:
                print(f"  - PNG icons: {png_count}")
            if other_count > 0:
                print(f"  - Other formats: {other_count}")

            # Open each existing icon
            print("\nOpening icons with default application...")
            for icon in icons:
                full_icon_path = os.path.join(dict_dir, icon)
                try:
                    open_file(full_icon_path)
                    print(f"  Opened: {icon}")
                except Exception as e:
                    print(f"  Failed to open {icon}: {e}")

        # If keys exist but no icons were generated (or all filtered out)
        elif keys:
            print("\n⚠️  Note: Keys exist but no matching icon files were found.")
            print(f"   Expected icons in: {dict_dir}")
            print("   Icons are generated by adding '.svg' to key names.")
            print("   Only files that actually exist are opened.")

    except ValueError as e:
        print(f"\nParsing error: {e}")
    except FileNotFoundError:
        print(f"\nError: File '{file_name}' could not be read.")
    except Exception as e:
        print(f"\nUnexpected error: {type(e).__name__}: {e}")

    # Pause so the user can see the results
    input("\nPress Enter to exit...")


if __name__ == "__main__":
    main()
    input("\nPress Enter to exit...")