def ayuda():
    print('Comandos disponibles en este nivel:')
    print('  circular   - Crea una matriz circular distribuyendo copias de un objeto en círculos concéntricos.')
    print('               Requiere: OBJ (objeto base), number (número de copias), number (ángulo), vector[] (centro), etc.')
    print('')
    print('  ortho      - Crea una matriz ortogonal de copias de un objeto en los ejes X, Y y Z.')
    print('               Requiere: OBJ (objeto base), vector[] (espaciado X), vector[] (espaciado Y), vector[] (espaciado Z),')
    print('                         number (cantidad X), number (cantidad Y), number (cantidad Z), bool (usar Link).')
    print('')
    print('  polar      - Crea una matriz polar distribuyendo copias de un objeto alrededor de un centro.')
    print('               Requiere: OBJ (objeto base), number (ángulo polar), number (cantidad de copias), vector[] (centro), bool (usar Link).')
    print('')
    print('  path       - Distribuye copias de un objeto a lo largo de una trayectoria o curva.')
    print('               Requiere: OBJ (objeto base), OBJ (trayectoria), number (cantidad de copias).')
    print('')
    print('  path_link  - Distribuye enlaces (Links) de un objeto a lo largo de una trayectoria o curva.')
    print('               Requiere: OBJ (objeto base), OBJ (trayectoria), number (cantidad de copias).')
    print('')
    print('  point      - Distribuye copias de un objeto en posiciones definidas por puntos.')
    print('               Requiere: OBJ (objeto base), OBJ (objeto contenedor de puntos / compuesto).')
    print('')
    print('  point_link - Distribuye enlaces (Links) de un objeto en las posiciones definidas por un conjunto de puntos.')
    print('               Requiere: OBJ (objeto base), OBJ (objeto contenedor de puntos / compuesto).')