def ayuda():
    print('Comandos disponibles en modify:')
    print('  fillet    - Redondea aristas seleccionadas de un sólido')
    print('  chamfer   - Aplica un chaflán sobre aristas seleccionadas')
    print('  draft     - Inclina caras de un sólido para facilitar el desmoldeo')
    print('  thickness - Vacía un sólido dejando paredes de grosor uniforme')
    print('  boolean   - Realiza operaciones booleanas (unión, resta, intersección) entre Bodies')
    print('\nPrecondiciones:')
    print('  - Todos los comandos requieren que exista un Body activo.')
    print('  - fillet y chamfer requieren seleccionar aristas (edges) previamente.')
    print('  - draft y thickness requieren seleccionar una o más caras (faces) previamente.')
    print('  - boolean requiere seleccionar otros Bodies para operar.')
